disabled_rules:
  - multiple_closures_with_trailing_closure
  - type_body_length
  - function_body_length
  - file_length
  - todo
opt_in_rules:
  - empty_count
  - convenience_type
  - empty_string
  - fatal_error_message
  - first_where
  - last_where
  - modifier_order
  - toggle_bool
  - fallthrough
  - identical_operands
  - joined_default_parameter
  - unavailable_function
  - overridden_super_call
  - control_statement
  - trailing_newline
  - colon
  - comma
  - class_delegate_protocol
  - closing_brace
  - duplicate_enum_cases
  - duplicate_imports
  - empty_parentheses_with_trailing_closure
  - for_where
  - implicitly_unwrapped_optional
  - unneeded_parentheses_in_closure_argument
  - unused_setter_value
  - unused_optional_binding
  - weak_delegate
  - yoda_condition
  - vertical_parameter_alignment_on_call
  - unused_import
  - unused_declaration
  - syntactic_sugar
  - redundant_void_return
  - redundant_optional_initialization
  - private_over_fileprivate
  - private_outlet
  - private_action
  - explicit_self
  - closure_spacing
  - explicit_init
  - mark
  - opening_brace
  - statement_position
  - switch_case_alignment
included:
  - MSLExamples
excluded:
  - Pods

warning_threshold: 1
force_cast: warning
force_try: warning
identifier_name:
  min_length: 1
type_name:
  min_length: 2
line_length:
  warning: 150
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
large_tuple:
  - 3
  - 4
nesting:
  type_level: 5
